gravatar:
  email: "username@email.com"
  size : 40

menu:
  - name: Home
    url : /
  - name: Categories
    url : /categories
  - name: Tags
    url : /tags
  - name: Profile
    url : http://profile.domain.com
  - name: Labs
    url : http://labs.domain.com
  - name: Github
    url : http://www.github.com/user
